/// Flutter icons KIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KIcons
///      fonts:
///       - asset: fonts/KIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KIcons {
  KIcons._();

  static const _kFontFam = 'KIcons';
  static const String? _kFontPkg = null;

  static const IconData organization = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pincode = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyright = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gst = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
